services:
    git_php.service.githandler:
        class: GitPhpBundle\DependencyInjection\GitHandler
        arguments: ["%repository_path%", "@git_php.service.filehandler"]
    git_php.service.filehandler:
        class: GitPhpBundle\DependencyInjection\FileHandler