<?php

namespace GitPhpBundle\Repository;

use GitPhpBundle\Entity\MergeRequest;

/**
 * MergeRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MergeRequestRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Create merge request entity entry
     *
     * @param string $sourceBranchName
     * @param string $commitHash
     * @param string $destinationBranchName
     */
    public function createMergeRequest($sourceBranchName, $commitHash, $destinationBranchName = "master")
    {
        $em = $this->getEntityManager();

        $mergeRequest = new MergeRequest();
        $mergeRequest->setSourceBranch($sourceBranchName);
        $mergeRequest->setCommitHash($commitHash);
        $mergeRequest->setDestinationBranch($destinationBranchName);
        $mergeRequest->setTimestamp();
        $em->persist($mergeRequest);
        $em->flush();
        $em->clear();
    }

    public function getMergeRequests()
    {
        $em = $this->getEntityManager();
    }
}
